# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Mork
version:      0.3
version_from: lib/File/Mork.pm
installdirs:  site
requires:
    HTML::Entities:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
